export enum EMIT_SOCKET {
    REGISTER_USER = 'REGISTER_USER',
    UNREGISTER_USER = 'UNREGISTER_USER',
}

export type EmitSocketType = `${EMIT_SOCKET}`;

export enum EMIT_USER_AGENT_CHAT {
    SEND_NEW_CHAT_MESSAGE = 'SEND_NEW_CHAT_MESSAGE',
    DELETE_CHAT_MESSAGE = 'DELETE_CHAT_MESSAGE',
    INCREASE_UNSEEN_MESSAGE_COUNT = 'INCREASE_UNSEEN_MESSAGE_COUNT',
    MARK_AS_SEEN = 'MARK_AS_SEEN',
}

export type EmitUserAgentChatType = `${EMIT_USER_AGENT_CHAT}`;

export enum SOCKET_NAMESPACES {
    USER_ONLINE = 'user-online',
}

export type SocketNamespaceType = `${SOCKET_NAMESPACES}`;